### ISSUE TITLE
Search Filters

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d-docs#50]
It might be useful to allow users to filter documentation searches.

As it is now, the search function of the documentation is indiscriminate: it produces results from both the API and the manual, from both page-titles and page-texts. This can, I've found, at times make it awkward to use, calling for one to comb through the results for the desired on.

Thus I suggest the addition of search filters: options to allow the user to search only in the API, only in the manual, only in page-titles, and only in page-text--and perhaps even only in class-names.

(PS: My apologies if you saw the initial, blank version of this issue--I managed to accidentally submit it partway through typing its name. ^^; )

**Comment by rdb** [comment]
It's a neat idea, but I fear that this would involve extensive changes to the Sphinx documentation generator.

**Comment by ArsThaumaturgis** [comment]
Ah, that is a pity! The current search really is awkward to use at the moment. ```:/```

Hmm... Would it be possible at least to indicate that the search be performed within a certain sub-set of the documentation--just within the API pages, or just within the manual pages, for example? That alone would be a significant boon, I feel.

**Comment by rdb** [comment]
Hmm, it does seem we are able to change the scoring algorithm so that matches in the title are preferred more heavily over partial matches or matches in the body of a document, or even, matches in the names of API objects.

For example, if I open the JS console, enter a class name in the search box, and quickly type `Scorer.objPartialMatch = 0; Scorer.objNameMatch = 0;` before it finishes the search, it seems to exclude some API matches.  Maybe this gives us an easy way to add such a switch, which would execute that JavaScript code.

Could you give me some examples of search terms that perform inadequately, in your opinion?

**Comment by rdb** [comment]
Hmm, upon further experimentation, it does somewhat alter the order but is not very satisfying. We can certainly change the scoring to more strongly prefer full title matches over partial matches, however.

One weird trick to exclude API results is to use the plural of a search term, eg. `NodePaths` will turn up results for NodePath in the manual but not the API page, because the stemming algorithm is applied to in-text and in-title searches but not for searches of object names.

**Comment by rdb** [comment]
Actually, it turns out that all the searching in Sphinx is done in one JS file, which we are already overriding, so maybe it is not such a problem to add our own functionality.

@ArsThaumaturgis I just updated the search feature on docs.panda3d.org, could you let me know whether this is more to your liking and whether you would like additional changes?

**Comment by ArsThaumaturgis** [comment]
Oh, that's much better indeed! Thank you very much! ^_^

The only further change that I'm inclined to suggest, if feasible, is a "search in titles only" check-box.

**Comment by rdb** [comment]
Done.
Other changes made:
* When already on search page, it no longer reloads when changing the search term, it instead updates as you type
* Results with terms matching the page title are always ranked higher than content matches

**Comment by ArsThaumaturgis** [comment]
That really is excellent, and a great improvement--thank you very much! :D
